# Generated by Django 4.1.6 on 2023-02-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(default=12.23, upload_to="pics"),
            preserve_default=False,
        ),
    ]
